#!/bin/sh /etc/rc.common
START=90
STOP=10

USE_PROCD=1
PROG="/usr/bin/pppwn"
VERSION=1001
OPTIONS="--interface br-lan --fw $VERSION --stage1 /etc/pppwn/stage1_${VERSION}.bin --stage2 /etc/pppwn/stage2_${VERSION}.bin --auto-retry"

start_service() {
        procd_open_instance
        procd_set_param command $PROG
        procd_append_param command $OPTIONS
        procd_set_param stdout 1
        procd_set_param stderr 1
        procd_set_param respawn
        procd_close_instance
}

stop_service()
{
        service_stop $PROG
}
